### ISSUE TITLE
Write new Met harvester to pull from their collections API

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme-harvest#11]
1. Iterate through pages of this request: `https://metmuseum.org/api/collection/collectionlisting?department=3&showOnly=openAccess` (`department=3` corresponds to the Ancient Near Eastern Art department)
1. Parse `url` key for each value in the results array and get the number located within it. E.g., for `/art/collection/search/326095?searchField=All&amp;sortBy=Relevance&amp;deptids=3&amp;ft=*&amp;offset=0&amp;rpp=20&amp;pos=2` get the number `326095`
1. Make a request to `https://collectionapi.metmuseum.org/public/collection/v1/objects/$OBJECT_NUMBER` for each object, e.g. `https://collectionapi.metmuseum.org/public/collection/v1/objects/326095` and save that to a new JSON file

**Comment by jcoyne** [comment]
Blocked by https://github.com/metmuseum/openaccess/issues/18

**Comment by anarchivist** [comment]
Here's another option:

1. Grab the Met's open access CSV from here: https://github.com/metmuseum/openaccess/blob/master/MetObjects.csv
1. For each  row where  `Department`  is `Ancient Near Eastern Art`, grab the `Object ID` value as `$OBJECT_ID` and grab JSON from `https://collectionapi.metmuseum.org/public/collection/v1/objects/$OBJECT_ID`, saving it to a JSON file
